version: '3'
services:

  app:
    container_name: app_graph
    build: api/
    command: flask run -h "0.0.0.0" -p 5000 --debugger --reload
    volumes:
      - ./src/:/app
      - ./api/shared:/app/shared
    links:
      - mongodb
    depends_on:
      - mongodb
    tty: true
    ports:
      - "5000:5000"
    env_file:
      - ./api/.envs

  mongodb:
    container_name: mongo_db
    hostname: db
    build: mongo/
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/shared:/data/shared
    tty: true
    environment:
      - MONGO_INITDB_DATABASE=amz_db
